ID-B-5
brinersam/Project-PET pull request #12
Opened 2024-09-25 17:36 UTC by brinersam

2024-09-25 18:02 UTC, YaraOduvanchik requested changes

2024-09-25 18:02 UTC, YaraOduvanchik commented on src/ProjectPet.Application/UseCases/CreateVolunteer/CreateVolunteerHandler.cs
> +            Volunteer result = Volunteer.Create(
Нужно проверить результат и вернуть ошибку, если результат будет IsFailure

2024-09-25 18:09 UTC, brinersam commented on src/ProjectPet.Application/UseCases/CreateVolunteer/CreateVolunteerHandler.cs
> +            try
Да понял, но я решил идти четко по заданиям и в 5.1 как раз и добавляется в проект класс Result который я распихаю везде где он нужен, а этот try-catch тут в роли затычки

2024-09-25 18:10 UTC, brinersam commented on src/ProjectPet.Application/UseCases/CreateVolunteer/CreateVolunteerHandler.cs
> +            Volunteer result = Volunteer.Create(
Добавлю Result в 5.1, сейчас воткну try catch как затычку

2024-09-26 04:05 UTC, YaraOduvanchik approved these changes

2024-09-26 16:25 UTC, merged